@startuml 注文処理

|顧客|
start
:新規の注文を
開始する;

repeat
  :注文に品目を
  追加する;
repeat while ([他に追加したい\n品目がある]) is (追加する\n品目\nがない)

repeat
  :決済をすませる;
  
  |信販会社|
  if () then ([利用\n限度額\n以上])
    :請求を
    拒否する;
    |顧客|
  else ([利用\n限度額\n未満])
    :請求を
    承認する;
    
    |出荷係員|
    :集荷を
    要求する;
    
    fork
      :注文を
      梱包する;
    fork again
      |配達員|
      :追跡番号を
      割り当てる;
    end fork
    
    |配達員|
    :注文を
    集荷する;
    
    :注文を
    配達する;
    
    stop
  endif
repeat while () is ()

@enduml